name: Replace-With-Your-Action-Name
description: Replace-With-Your-Action-Description
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Build with Maven
      shell: bash
      run: |
        cd base_code
        mvn -B package --file pom.xml